// frontend_vue/src/components/NavBar.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="#">Task Manager</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <AddTask :setReload="setReload" />
          </li>
          <li class="nav-item dropdown">
            <div
              v-if="user"
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              Signed in as: {{ user.user.name }}
            </div>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" @click="logout" href="#">Log out</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script>
import { defineComponent, ref } from "vue";
import axios from "axios";
import { useRouter } from "vue-router";
import AddTask from "./modals/AddTask.vue";

export default defineComponent({
  props: {
    setReload: Function,
  },
  components: {
    AddTask,
  },
  setup(props) {
    const user = ref(JSON.parse(localStorage.getItem("userInfo"))).value;
    const router = useRouter();

    const logout = async () => {
      try {
        await axios.post(
          `http://localhost:8000/api/logout`,
          {},
          {
            headers: {
              Authorization: `Bearer ${user.token}`,
            },
          }
        );
        localStorage.clear();
        router.push("/");
      } catch (err) {
        console.error(err.message);
      }
    };

    return {
      user,
      logout,
    };
  },
});
</script>

// frontend/src/components/NavBar.jsx
import React from "react";
import { Navbar, Container, NavDropdown } from "react-bootstrap";
import AddTask from "./modals/AddTask";
import axios from "axios";
import { useNavigate } from "react-router-dom";

const NavBar = ({ setReload }) => {
  const user = JSON.parse(localStorage.getItem("userInfo"));
  const navigate = useNavigate()
  const logout = async () => {
    try {
      await axios.post(
        `${process.env.REACT_APP_API_URL}/api/logout`,
        {},
        {
          headers: {
            Authorization: `Bearer ${user.token}`,
          },
        }
      );
      localStorage.clear();
      navigate('/');
    } catch (err) {
      console.log(err.message);
    }
  };
  return (
    <>
      <Navbar className="bg-body-tertiary">
        <Container>
          <Navbar.Brand href="#home">
            <AddTask setReload={setReload} />
          </Navbar.Brand>
          <Navbar.Toggle />
          <Navbar.Collapse className="justify-content-end">
            <Navbar.Text>
              <NavDropdown
                title={`Signed in as: ${user? user.user.name: ""}`}
                id="basic-nav-dropdown"
              >
                <NavDropdown.Item onClick={logout}>Log out</NavDropdown.Item>
              </NavDropdown>
            </Navbar.Text>
          </Navbar.Collapse>
        </Container>
      </Navbar>
    </>
  );
};

export default NavBar;
