// frontend/src/components/modals/EditTask.jsx
import React from "react";
import { useState } from "react";
import { Modal, Button, Table } from "react-bootstrap";
import axios from "axios";

const EditTask = ({task,setReload}) => {
  const [show, setShow] = useState(false);
  const [name, setName] = useState(task.name);
  const [description, setDescription] = useState(task.description);
  const [priority, setPriority] = useState(task.priority);
  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  const handleSubmit = async () => {
    try {
        let token = JSON.parse(localStorage.getItem("userInfo")).token;
      await axios
        .patch(
          `${process.env.REACT_APP_API_URL}/api/task/${task.id}`,
          {
            name: name,
            description: description,
            priority: priority,
          },
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        )
        .then(() => setReload(true));
        handleClose();
    } catch (err) {
      console.log(err.message);
    }
  };

  return (
    <>
      <Button variant="primary" onClick={handleShow}>
        Edit
      </Button>

      <Modal show={show} onHide={handleClose} size="lg">
        <Modal.Header closeButton>
          <Modal.Title>Edit Task</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <div className="table-responsive">
            <Table striped bordered hover>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Priority</th>
                </tr>
              </thead>
              <tbody>
                <tr key={task.id}>
                  <td>
                    <input
                      value={name}
                      type="text"
                      id="name"
                      name="name"
                      onChange={(e) => setName(e.target.value)}
                    />
                  </td>
                  <td>
                    <input
                      value={description}
                      type="text"
                      id="description"
                      name="description"
                      onChange={(e) => setDescription(e.target.value)}
                    />
                  </td>
                  <td>
                    <input
                      value={priority}
                      type="text"
                      id="priority"
                      name="priority"
                      onChange={(e) => setPriority(e.target.value)}
                    />
                  </td>
                </tr>
              </tbody>
            </Table>
          </div>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose}>
            Close
          </Button>
          <Button variant="primary" onClick={handleSubmit}>
            Save Changes
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  );
};

export default EditTask;

// frontend_vue/src/components/modals/EditTask.vue
<template>
  <div>
    <button class="btn btn-primary" @click="handleShow">Edit</button>

    <div
      v-if="show"
      class="modal"
      tabindex="-1"
      role="dialog"
      style="display: block"
    >
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Edit Task</h5>
            <button
              type="button"
              class="close"
              @click="handleClose"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Priority</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      <input
                        v-model="name"
                        type="text"
                        class="form-control"
                        id="name"
                        name="name"
                      />
                    </td>
                    <td>
                      <input
                        v-model="description"
                        type="text"
                        class="form-control"
                        id="description"
                        name="description"
                      />
                    </td>
                    <td>
                      <input
                        v-model="priority"
                        type="text"
                        class="form-control"
                        id="priority"
                        name="priority"
                      />
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              @click="handleClose"
            >
              Close
            </button>
            <button type="button" class="btn btn-primary" @click="handleSubmit">
              Save Changes
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import axios from "axios";

export default defineComponent({
  props: {
    task: Object,
    setReload: Function,
  },
  setup(props) {
    const show = ref(false);
    const name = ref(props.task?.name);
    const description = ref(props.task?.description);
    const priority = ref(props.task?.priority);

    const handleClose = () => {
      show.value = false;
    };

    const handleShow = () => {
      show.value = true;
    };

    const handleSubmit = async () => {
      try {
        const token = JSON.parse(localStorage.getItem("userInfo") || "").token;
        await axios.patch(
          `${process.env.VUE_APP_API_URL}/api/task/${props.task?.id}`,
          {
            name: name.value,
            description: description.value,
            priority: priority.value,
          },
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );
        if (props.setReload) {
          props.setReload(true);
        }

        handleClose();
      } catch (err) {
        console.error((err as Error).message);
      }
    };

    return {
      show,
      name,
      description,
      priority,
      handleClose,
      handleShow,
      handleSubmit,
    };
  },
});
</script>

<style scoped>
/* Add your styles here */
</style>
